export const ALL_COLUMNS = [
  { key: "estado", label: "Estado", width: 90 },
  { key: "tipo", label: "Tipo", width: 80 },
  { key: "numero", label: "Número", width: 110 },
  { key: "fecha", label: "Fecha", width: 100 },
  { key: "emisor", label: "Emisor", width: 180 },
  { key: "nif", label: "NIF", width: 110 },
  { key: "base21", label: "Base 21%", width: 100 },
  { key: "iva21", label: "IVA 21%", width: 90 },
  { key: "base12", label: "Base 12%", width: 100 },
  { key: "iva12", label: "IVA 12%", width: 90 },
  { key: "base10_5", label: "Base 10,5%", width: 100 },
  { key: "iva10_5", label: "IVA 10,5%", width: 90 },
  { key: "base10", label: "Base 10%", width: 100 },
  { key: "iva10", label: "IVA 10%", width: 90 },
  { key: "base5", label: "Base 5%", width: 100 },
  { key: "iva5", label: "IVA 5%", width: 90 },
  { key: "base4", label: "Base 4%", width: 100 },
  { key: "iva4", label: "IVA 4%", width: 90 },
  { key: "base0", label: "Base 0%", width: 100 },
  { key: "base0ne", label: "Base 0% NE", width: 100 },
  { key: "iva0ne", label: "IVA 0% NE", width: 90 },
  { key: "base0ns", label: "Base 0% NS", width: 100 },
  { key: "iva0ns", label: "IVA 0% NS", width: 90 },
  { key: "metpago", label: "Mét. Pago", width: 100 },
  { key: "pctret", label: "% Ret.", width: 80 },
  { key: "ret", label: "Retención", width: 100 },
  { key: "total", label: "Total", width: 100 },
  { key: "cuenta", label: "Cuenta", width: 100 },
  { key: "confianza", label: "Confianza", width: 90 },
];

export const DEFAULT_VISIBLE_COLUMNS = [
  "estado",
  "tipo",
  "numero",
  "fecha",
  "emisor",
  "nif",
  "base21",
  "iva21",
  "base10",
  "iva10",
  "base4",
  "iva4",
  "base0",
  "ret",
  "total",
  "cuenta",
  "confianza",
];
