const PGC = [
  // GRUPO 1 - FINANCIACIÓN BÁSICA
  { codigo: "10", nombre: "Capital", grupo: 1 },
  { codigo: "100", nombre: "Capital social", grupo: 1 },
  { codigo: "101", nombre: "Fondo social", grupo: 1 },
  { codigo: "102", nombre: "Capital", grupo: 1 },
  { codigo: "103", nombre: "Socios por desembolsos no exigidos", grupo: 1 },
  { codigo: "104", nombre: "Socios por aportaciones no dinerarias pendientes", grupo: 1 },
  { codigo: "108", nombre: "Acciones o participaciones propias en situaciones especiales", grupo: 1 },
  { codigo: "109", nombre: "Acciones o participaciones propias para reducción de capital", grupo: 1 },
  { codigo: "11", nombre: "Reservas y otros instrumentos de patrimonio", grupo: 1 },
  { codigo: "110", nombre: "Prima de emisión o asunción", grupo: 1 },
  { codigo: "111", nombre: "Otros instrumentos de patrimonio neto", grupo: 1 },
  { codigo: "112", nombre: "Reserva legal", grupo: 1 },
  { codigo: "113", nombre: "Reservas voluntarias", grupo: 1 },
  { codigo: "114", nombre: "Reservas especiales", grupo: 1 },
  { codigo: "118", nombre: "Aportaciones de socios o propietarios", grupo: 1 },
  { codigo: "119", nombre: "Diferencias por ajuste del capital a euros", grupo: 1 },
  { codigo: "12", nombre: "Resultados pendientes de aplicación", grupo: 1 },
  { codigo: "120", nombre: "Remanente", grupo: 1 },
  { codigo: "121", nombre: "Resultados negativos de ejercicios anteriores", grupo: 1 },
  { codigo: "129", nombre: "Resultado del ejercicio", grupo: 1 },
  { codigo: "13", nombre: "Subvenciones, donaciones y ajustes por cambios de valor", grupo: 1 },
  { codigo: "130", nombre: "Subvenciones oficiales de capital", grupo: 1 },
  { codigo: "131", nombre: "Donaciones y legados de capital", grupo: 1 },
  { codigo: "132", nombre: "Otras subvenciones, donaciones y legados", grupo: 1 },
  { codigo: "133", nombre: "Ajustes por valoración en activos financieros a valor razonable", grupo: 1 },
  { codigo: "134", nombre: "Operaciones de cobertura", grupo: 1 },
  { codigo: "135", nombre: "Diferencias de conversión", grupo: 1 },
  { codigo: "136", nombre: "Ajustes por valoración en activos no corrientes mantenidos para la venta", grupo: 1 },
  { codigo: "137", nombre: "Ingresos fiscales a distribuir en varios ejercicios", grupo: 1 },
  { codigo: "14", nombre: "Provisiones", grupo: 1 },
  { codigo: "140", nombre: "Provisión por retribuciones a largo plazo al personal", grupo: 1 },
  { codigo: "141", nombre: "Provisión para impuestos", grupo: 1 },
  { codigo: "142", nombre: "Provisión para otras responsabilidades", grupo: 1 },
  { codigo: "143", nombre: "Provisión por desmantelamiento, retiro o rehabilitación del inmovilizado", grupo: 1 },
  { codigo: "145", nombre: "Provisión para actuaciones medioambientales", grupo: 1 },
  { codigo: "15", nombre: "Deudas a largo plazo con características especiales", grupo: 1 },
  { codigo: "150", nombre: "Acciones o participaciones a l/p consideradas como pasivos financieros", grupo: 1 },
  { codigo: "153", nombre: "Desembolsos no exigidos por acciones a l/p como pasivos financieros", grupo: 1 },
  { codigo: "16", nombre: "Deudas a largo plazo con partes vinculadas", grupo: 1 },
  { codigo: "160", nombre: "Deudas a l/p con entidades de crédito vinculadas", grupo: 1 },
  { codigo: "161", nombre: "Proveedores de inmovilizado a l/p, partes vinculadas", grupo: 1 },
  { codigo: "162", nombre: "Acreedores por arrendamiento financiero a l/p, partes vinculadas", grupo: 1 },
  { codigo: "163", nombre: "Otras deudas a l/p con partes vinculadas", grupo: 1 },
  { codigo: "17", nombre: "Deudas a largo plazo por préstamos recibidos y otros conceptos", grupo: 1 },
  { codigo: "170", nombre: "Deudas a l/p con entidades de crédito", grupo: 1 },
  { codigo: "171", nombre: "Deudas a largo plazo", grupo: 1 },
  { codigo: "172", nombre: "Deudas a l/p transformables en subvenciones", grupo: 1 },
  { codigo: "173", nombre: "Proveedores de inmovilizado a largo plazo", grupo: 1 },
  { codigo: "174", nombre: "Acreedores por arrendamiento financiero a largo plazo", grupo: 1 },
  { codigo: "175", nombre: "Efectos a pagar a largo plazo", grupo: 1 },
  { codigo: "176", nombre: "Pasivos por derivados financieros a largo plazo", grupo: 1 },
  { codigo: "177", nombre: "Obligaciones y bonos", grupo: 1 },
  { codigo: "178", nombre: "Deudas por efectos descontados", grupo: 1 },
  { codigo: "179", nombre: "Deudas representadas en otros valores negociables", grupo: 1 },
  { codigo: "18", nombre: "Pasivos por fianzas, garantías y otros conceptos a largo plazo", grupo: 1 },
  { codigo: "180", nombre: "Fianzas recibidas a largo plazo", grupo: 1 },
  { codigo: "181", nombre: "Anticipos recibidos por ventas o prestaciones de servicios a l/p", grupo: 1 },
  { codigo: "185", nombre: "Depósitos recibidos a largo plazo", grupo: 1 },
  { codigo: "189", nombre: "Garantías financieras a largo plazo", grupo: 1 },
  { codigo: "19", nombre: "Situaciones transitorias de financiación", grupo: 1 },
  { codigo: "190", nombre: "Acciones o participaciones emitidas", grupo: 1 },
  { codigo: "192", nombre: "Suscriptores de acciones", grupo: 1 },
  { codigo: "194", nombre: "Capital emitido pendiente de inscripción", grupo: 1 },

  // GRUPO 2 - ACTIVO NO CORRIENTE
  { codigo: "20", nombre: "Inmovilizaciones intangibles", grupo: 2 },
  { codigo: "200", nombre: "Investigación", grupo: 2 },
  { codigo: "201", nombre: "Desarrollo", grupo: 2 },
  { codigo: "202", nombre: "Concesiones administrativas", grupo: 2 },
  { codigo: "203", nombre: "Propiedad industrial", grupo: 2 },
  { codigo: "204", nombre: "Fondo de comercio", grupo: 2 },
  { codigo: "205", nombre: "Derechos de traspaso", grupo: 2 },
  { codigo: "206", nombre: "Aplicaciones informáticas", grupo: 2 },
  { codigo: "209", nombre: "Anticipos para inmovilizaciones intangibles", grupo: 2 },
  { codigo: "21", nombre: "Inmovilizaciones materiales", grupo: 2 },
  { codigo: "210", nombre: "Terrenos y bienes naturales", grupo: 2 },
  { codigo: "211", nombre: "Construcciones", grupo: 2 },
  { codigo: "212", nombre: "Instalaciones técnicas", grupo: 2 },
  { codigo: "213", nombre: "Maquinaria", grupo: 2 },
  { codigo: "214", nombre: "Utillaje", grupo: 2 },
  { codigo: "215", nombre: "Otras instalaciones", grupo: 2 },
  { codigo: "216", nombre: "Mobiliario", grupo: 2 },
  { codigo: "217", nombre: "Equipos para procesos de información", grupo: 2 },
  { codigo: "218", nombre: "Elementos de transporte", grupo: 2 },
  { codigo: "219", nombre: "Otro inmovilizado material", grupo: 2 },
  { codigo: "22", nombre: "Inversiones inmobiliarias", grupo: 2 },
  { codigo: "220", nombre: "Inversiones en terrenos y bienes naturales", grupo: 2 },
  { codigo: "221", nombre: "Inversiones en construcciones", grupo: 2 },
  { codigo: "23", nombre: "Inmovilizaciones materiales en curso", grupo: 2 },
  { codigo: "230", nombre: "Adaptación de terrenos y bienes naturales", grupo: 2 },
  { codigo: "231", nombre: "Construcciones en curso", grupo: 2 },
  { codigo: "232", nombre: "Instalaciones técnicas en montaje", grupo: 2 },
  { codigo: "233", nombre: "Maquinaria en montaje", grupo: 2 },
  { codigo: "237", nombre: "Equipos para procesos de información en montaje", grupo: 2 },
  { codigo: "239", nombre: "Anticipos para inmovilizaciones materiales", grupo: 2 },
  { codigo: "24", nombre: "Inversiones financieras a largo plazo en partes vinculadas", grupo: 2 },
  { codigo: "240", nombre: "Participaciones a l/p en partes vinculadas", grupo: 2 },
  { codigo: "241", nombre: "Valores representativos de deuda a l/p de partes vinculadas", grupo: 2 },
  { codigo: "242", nombre: "Créditos a l/p a partes vinculadas", grupo: 2 },
  { codigo: "249", nombre: "Desembolsos pendientes sobre participaciones a l/p en partes vinculadas", grupo: 2 },
  { codigo: "25", nombre: "Otras inversiones financieras a largo plazo", grupo: 2 },
  { codigo: "250", nombre: "Inversiones financieras a l/p en instrumentos de patrimonio", grupo: 2 },
  { codigo: "251", nombre: "Valores representativos de deuda a largo plazo", grupo: 2 },
  { codigo: "252", nombre: "Créditos a largo plazo", grupo: 2 },
  { codigo: "253", nombre: "Créditos a l/p por enajenación de inmovilizado", grupo: 2 },
  { codigo: "254", nombre: "Créditos a l/p al personal", grupo: 2 },
  { codigo: "255", nombre: "Activos por derivados financieros a largo plazo", grupo: 2 },
  { codigo: "258", nombre: "Imposiciones a largo plazo", grupo: 2 },
  { codigo: "259", nombre: "Desembolsos pendientes sobre participaciones en el patrimonio neto a l/p", grupo: 2 },
  { codigo: "26", nombre: "Fianzas y depósitos constituidos a largo plazo", grupo: 2 },
  { codigo: "260", nombre: "Fianzas constituidas a largo plazo", grupo: 2 },
  { codigo: "265", nombre: "Depósitos constituidos a largo plazo", grupo: 2 },
  { codigo: "28", nombre: "Amortización acumulada del inmovilizado", grupo: 2 },
  { codigo: "280", nombre: "Amortización acumulada del inmovilizado intangible", grupo: 2 },
  { codigo: "281", nombre: "Amortización acumulada del inmovilizado material", grupo: 2 },
  { codigo: "282", nombre: "Amortización acumulada de inversiones inmobiliarias", grupo: 2 },
  { codigo: "29", nombre: "Deterioro de valor de activos no corrientes", grupo: 2 },
  { codigo: "290", nombre: "Deterioro de valor del inmovilizado intangible", grupo: 2 },
  { codigo: "291", nombre: "Deterioro de valor del inmovilizado material", grupo: 2 },
  { codigo: "292", nombre: "Deterioro de valor de inversiones inmobiliarias", grupo: 2 },
  { codigo: "293", nombre: "Deterioro de valor de participaciones a l/p en partes vinculadas", grupo: 2 },
  { codigo: "294", nombre: "Deterioro de valor de valores representativos de deuda a l/p de partes vinculadas", grupo: 2 },
  { codigo: "295", nombre: "Deterioro de valor de créditos a l/p a partes vinculadas", grupo: 2 },
  { codigo: "296", nombre: "Deterioro de valor de participaciones en el patrimonio neto a l/p", grupo: 2 },
  { codigo: "297", nombre: "Deterioro de valor de valores representativos de deuda a l/p", grupo: 2 },
  { codigo: "298", nombre: "Deterioro de valor de créditos a largo plazo", grupo: 2 },

  // GRUPO 3 - EXISTENCIAS
  { codigo: "30", nombre: "Comerciales", grupo: 3 },
  { codigo: "300", nombre: "Mercaderías A", grupo: 3 },
  { codigo: "301", nombre: "Mercaderías B", grupo: 3 },
  { codigo: "31", nombre: "Materias primas", grupo: 3 },
  { codigo: "310", nombre: "Materias primas A", grupo: 3 },
  { codigo: "311", nombre: "Materias primas B", grupo: 3 },
  { codigo: "32", nombre: "Otros aprovisionamientos", grupo: 3 },
  { codigo: "320", nombre: "Elementos y conjuntos incorporables", grupo: 3 },
  { codigo: "321", nombre: "Combustibles", grupo: 3 },
  { codigo: "322", nombre: "Repuestos", grupo: 3 },
  { codigo: "325", nombre: "Materiales diversos", grupo: 3 },
  { codigo: "326", nombre: "Embalajes", grupo: 3 },
  { codigo: "327", nombre: "Envases", grupo: 3 },
  { codigo: "328", nombre: "Material de oficina", grupo: 3 },
  { codigo: "33", nombre: "Productos en curso", grupo: 3 },
  { codigo: "330", nombre: "Productos en curso A", grupo: 3 },
  { codigo: "34", nombre: "Productos semiterminados", grupo: 3 },
  { codigo: "340", nombre: "Productos semiterminados A", grupo: 3 },
  { codigo: "35", nombre: "Productos terminados", grupo: 3 },
  { codigo: "350", nombre: "Productos terminados A", grupo: 3 },
  { codigo: "36", nombre: "Subproductos, residuos y materiales recuperados", grupo: 3 },
  { codigo: "360", nombre: "Subproductos A", grupo: 3 },
  { codigo: "365", nombre: "Residuos A", grupo: 3 },
  { codigo: "368", nombre: "Materiales recuperados A", grupo: 3 },
  { codigo: "39", nombre: "Deterioro de valor de las existencias", grupo: 3 },
  { codigo: "390", nombre: "Deterioro de valor de mercaderías", grupo: 3 },
  { codigo: "391", nombre: "Deterioro de valor de materias primas", grupo: 3 },
  { codigo: "392", nombre: "Deterioro de valor de otros aprovisionamientos", grupo: 3 },
  { codigo: "393", nombre: "Deterioro de valor de productos en curso", grupo: 3 },
  { codigo: "394", nombre: "Deterioro de valor de productos semiterminados", grupo: 3 },
  { codigo: "395", nombre: "Deterioro de valor de productos terminados", grupo: 3 },
  { codigo: "396", nombre: "Deterioro de valor de subproductos, residuos y materiales recuperados", grupo: 3 },

  // GRUPO 4 - ACREEDORES Y DEUDORES POR OPERACIONES COMERCIALES
  { codigo: "40", nombre: "Proveedores", grupo: 4 },
  { codigo: "400", nombre: "Proveedores", grupo: 4 },
  { codigo: "401", nombre: "Proveedores, efectos comerciales a pagar", grupo: 4 },
  { codigo: "403", nombre: "Proveedores, partes vinculadas", grupo: 4 },
  { codigo: "404", nombre: "Proveedores por facturas pendientes de recibir o de formalizar", grupo: 4 },
  { codigo: "405", nombre: "Proveedores, partes vinculadas, efectos comerciales a pagar", grupo: 4 },
  { codigo: "406", nombre: "Envases y embalajes a devolver a proveedores", grupo: 4 },
  { codigo: "407", nombre: "Anticipos a proveedores", grupo: 4 },
  { codigo: "41", nombre: "Acreedores varios", grupo: 4 },
  { codigo: "410", nombre: "Acreedores por prestaciones de servicios", grupo: 4 },
  { codigo: "411", nombre: "Acreedores, efectos comerciales a pagar", grupo: 4 },
  { codigo: "419", nombre: "Acreedores por operaciones en común", grupo: 4 },
  { codigo: "43", nombre: "Clientes", grupo: 4 },
  { codigo: "430", nombre: "Clientes", grupo: 4 },
  { codigo: "431", nombre: "Clientes, efectos comerciales a cobrar", grupo: 4 },
  { codigo: "432", nombre: "Clientes, operaciones de factoring", grupo: 4 },
  { codigo: "433", nombre: "Clientes, partes vinculadas", grupo: 4 },
  { codigo: "434", nombre: "Clientes por facturas pendientes de formalizar", grupo: 4 },
  { codigo: "435", nombre: "Clientes, partes vinculadas, efectos comerciales a cobrar", grupo: 4 },
  { codigo: "436", nombre: "Envases y embalajes a devolver por clientes", grupo: 4 },
  { codigo: "437", nombre: "Anticipos de clientes", grupo: 4 },
  { codigo: "44", nombre: "Deudores varios", grupo: 4 },
  { codigo: "440", nombre: "Deudores", grupo: 4 },
  { codigo: "441", nombre: "Deudores, efectos comerciales a cobrar", grupo: 4 },
  { codigo: "449", nombre: "Deudores por operaciones en común", grupo: 4 },
  { codigo: "46", nombre: "Personal", grupo: 4 },
  { codigo: "460", nombre: "Anticipos de remuneraciones", grupo: 4 },
  { codigo: "465", nombre: "Remuneraciones pendientes de pago", grupo: 4 },
  { codigo: "47", nombre: "Administraciones Públicas", grupo: 4 },
  { codigo: "470", nombre: "Hacienda Pública, deudora por diversos conceptos", grupo: 4 },
  { codigo: "471", nombre: "Organismos de la Seguridad Social, deudores", grupo: 4 },
  { codigo: "472", nombre: "Hacienda Pública, IVA soportado", grupo: 4 },
  { codigo: "473", nombre: "Hacienda Pública, retenciones y pagos a cuenta", grupo: 4 },
  { codigo: "474", nombre: "Activos por impuesto diferido", grupo: 4 },
  { codigo: "475", nombre: "Hacienda Pública, acreedora por conceptos fiscales", grupo: 4 },
  { codigo: "476", nombre: "Organismos de la Seguridad Social, acreedores", grupo: 4 },
  { codigo: "477", nombre: "Hacienda Pública, IVA repercutido", grupo: 4 },
  { codigo: "479", nombre: "Pasivos por diferencias temporarias imponibles", grupo: 4 },
  { codigo: "48", nombre: "Ajustes por periodificación", grupo: 4 },
  { codigo: "480", nombre: "Gastos anticipados", grupo: 4 },
  { codigo: "485", nombre: "Ingresos anticipados", grupo: 4 },
  { codigo: "49", nombre: "Deterioro de valor de créditos comerciales y provisiones a c/p", grupo: 4 },
  { codigo: "490", nombre: "Deterioro de valor de créditos por operaciones comerciales", grupo: 4 },
  { codigo: "493", nombre: "Provisión por operaciones comerciales", grupo: 4 },
  { codigo: "499", nombre: "Provisión para otras operaciones comerciales", grupo: 4 },

  // GRUPO 5 - CUENTAS FINANCIERAS
  { codigo: "50", nombre: "Empréstitos, deudas con características especiales y otras emisiones análogas a c/p", grupo: 5 },
  { codigo: "500", nombre: "Obligaciones y bonos a corto plazo", grupo: 5 },
  { codigo: "501", nombre: "Obligaciones y bonos convertibles a corto plazo", grupo: 5 },
  { codigo: "505", nombre: "Deudas representadas en otros valores negociables a c/p", grupo: 5 },
  { codigo: "506", nombre: "Intereses a c/p de empréstitos y otras emisiones análogas", grupo: 5 },
  { codigo: "507", nombre: "Dividendos activos a pagar", grupo: 5 },
  { codigo: "509", nombre: "Valores negociables amortizados", grupo: 5 },
  { codigo: "51", nombre: "Deudas a corto plazo con partes vinculadas", grupo: 5 },
  { codigo: "510", nombre: "Deudas a c/p con entidades de crédito vinculadas", grupo: 5 },
  { codigo: "511", nombre: "Proveedores de inmovilizado a c/p, partes vinculadas", grupo: 5 },
  { codigo: "512", nombre: "Acreedores por arrendamiento financiero a c/p, partes vinculadas", grupo: 5 },
  { codigo: "513", nombre: "Otras deudas a c/p con partes vinculadas", grupo: 5 },
  { codigo: "514", nombre: "Intereses a c/p de deudas con partes vinculadas", grupo: 5 },
  { codigo: "52", nombre: "Deudas a corto plazo por préstamos recibidos y otros conceptos", grupo: 5 },
  { codigo: "520", nombre: "Deudas a c/p con entidades de crédito", grupo: 5 },
  { codigo: "521", nombre: "Deudas a corto plazo", grupo: 5 },
  { codigo: "522", nombre: "Deudas a c/p transformables en subvenciones", grupo: 5 },
  { codigo: "523", nombre: "Proveedores de inmovilizado a corto plazo", grupo: 5 },
  { codigo: "524", nombre: "Acreedores por arrendamiento financiero a corto plazo", grupo: 5 },
  { codigo: "525", nombre: "Efectos a pagar a corto plazo", grupo: 5 },
  { codigo: "526", nombre: "Dividendo activo a pagar", grupo: 5 },
  { codigo: "527", nombre: "Intereses a c/p de deudas con entidades de crédito", grupo: 5 },
  { codigo: "528", nombre: "Intereses a c/p de deudas", grupo: 5 },
  { codigo: "529", nombre: "Provisiones a corto plazo", grupo: 5 },
  { codigo: "53", nombre: "Inversiones financieras a corto plazo en partes vinculadas", grupo: 5 },
  { codigo: "530", nombre: "Participaciones a c/p en partes vinculadas", grupo: 5 },
  { codigo: "531", nombre: "Valores representativos de deuda a c/p de partes vinculadas", grupo: 5 },
  { codigo: "532", nombre: "Créditos a c/p a partes vinculadas", grupo: 5 },
  { codigo: "533", nombre: "Intereses a c/p de valores representativos de deuda de partes vinculadas", grupo: 5 },
  { codigo: "534", nombre: "Intereses a c/p de créditos a partes vinculadas", grupo: 5 },
  { codigo: "535", nombre: "Dividendo a cobrar de inversiones financieras en partes vinculadas", grupo: 5 },
  { codigo: "539", nombre: "Desembolsos pendientes sobre participaciones a c/p en partes vinculadas", grupo: 5 },
  { codigo: "54", nombre: "Otras inversiones financieras a corto plazo", grupo: 5 },
  { codigo: "540", nombre: "Inversiones financieras a c/p en instrumentos de patrimonio", grupo: 5 },
  { codigo: "541", nombre: "Valores representativos de deuda a corto plazo", grupo: 5 },
  { codigo: "542", nombre: "Créditos a corto plazo", grupo: 5 },
  { codigo: "543", nombre: "Créditos a c/p por enajenación de inmovilizado", grupo: 5 },
  { codigo: "544", nombre: "Créditos a c/p al personal", grupo: 5 },
  { codigo: "545", nombre: "Dividendo a cobrar", grupo: 5 },
  { codigo: "546", nombre: "Intereses a c/p de valores representativos de deuda", grupo: 5 },
  { codigo: "547", nombre: "Intereses a c/p de créditos", grupo: 5 },
  { codigo: "548", nombre: "Imposiciones a corto plazo", grupo: 5 },
  { codigo: "549", nombre: "Desembolsos pendientes sobre participaciones en el patrimonio neto a c/p", grupo: 5 },
  { codigo: "55", nombre: "Otras cuentas no bancarias", grupo: 5 },
  { codigo: "550", nombre: "Titular de la explotación", grupo: 5 },
  { codigo: "551", nombre: "Cuenta corriente con socios y administradores", grupo: 5 },
  { codigo: "552", nombre: "Cuenta corriente con otras personas y entidades vinculadas", grupo: 5 },
  { codigo: "555", nombre: "Partidas pendientes de aplicación", grupo: 5 },
  { codigo: "556", nombre: "Desembolsos exigidos sobre participaciones en el patrimonio neto", grupo: 5 },
  { codigo: "557", nombre: "Dividendo activo a cuenta", grupo: 5 },
  { codigo: "558", nombre: "Socios por desembolsos exigidos", grupo: 5 },
  { codigo: "559", nombre: "Derivados financieros a corto plazo", grupo: 5 },
  { codigo: "56", nombre: "Fianzas y depósitos recibidos y constituidos a c/p y ajustes por periodificación", grupo: 5 },
  { codigo: "560", nombre: "Fianzas recibidas a corto plazo", grupo: 5 },
  { codigo: "561", nombre: "Depósitos recibidos a corto plazo", grupo: 5 },
  { codigo: "565", nombre: "Fianzas constituidas a corto plazo", grupo: 5 },
  { codigo: "566", nombre: "Depósitos constituidos a corto plazo", grupo: 5 },
  { codigo: "567", nombre: "Intereses pagados por anticipado", grupo: 5 },
  { codigo: "568", nombre: "Intereses cobrados por anticipado", grupo: 5 },
  { codigo: "57", nombre: "Tesorería", grupo: 5 },
  { codigo: "570", nombre: "Caja, euros", grupo: 5 },
  { codigo: "571", nombre: "Caja, moneda extranjera", grupo: 5 },
  { codigo: "572", nombre: "Bancos e instituciones de crédito c/c vista, euros", grupo: 5 },
  { codigo: "573", nombre: "Bancos e instituciones de crédito c/c vista, moneda extranjera", grupo: 5 },
  { codigo: "574", nombre: "Bancos e instituciones de crédito, cuentas de ahorro, euros", grupo: 5 },
  { codigo: "575", nombre: "Bancos e instituciones de crédito, cuentas de ahorro, moneda extranjera", grupo: 5 },
  { codigo: "576", nombre: "Inversiones a c/p de gran liquidez", grupo: 5 },
  { codigo: "58", nombre: "Activos no corrientes mantenidos para la venta y activos y pasivos asociados", grupo: 5 },
  { codigo: "580", nombre: "Inmovilizado", grupo: 5 },
  { codigo: "581", nombre: "Inversiones con personas y entidades vinculadas", grupo: 5 },
  { codigo: "582", nombre: "Inversiones financieras", grupo: 5 },
  { codigo: "583", nombre: "Existencias, deudores comerciales y otros activos", grupo: 5 },
  { codigo: "584", nombre: "Otros activos", grupo: 5 },
  { codigo: "585", nombre: "Provisiones", grupo: 5 },
  { codigo: "586", nombre: "Deudas con características especiales", grupo: 5 },
  { codigo: "587", nombre: "Deudas con personas o entidades vinculadas", grupo: 5 },
  { codigo: "588", nombre: "Acreedores comerciales y otras cuentas a pagar", grupo: 5 },
  { codigo: "589", nombre: "Otros pasivos", grupo: 5 },
  { codigo: "59", nombre: "Deterioro del valor de inversiones financieras a c/p", grupo: 5 },
  { codigo: "593", nombre: "Deterioro de valor de participaciones a c/p en partes vinculadas", grupo: 5 },
  { codigo: "594", nombre: "Deterioro de valor de valores representativos de deuda a c/p de partes vinculadas", grupo: 5 },
  { codigo: "595", nombre: "Deterioro de valor de créditos a c/p a partes vinculadas", grupo: 5 },
  { codigo: "596", nombre: "Deterioro de valor de participaciones en el patrimonio neto a c/p", grupo: 5 },
  { codigo: "597", nombre: "Deterioro de valor de valores representativos de deuda a c/p", grupo: 5 },
  { codigo: "598", nombre: "Deterioro de valor de créditos a corto plazo", grupo: 5 },

  // GRUPO 6 - COMPRAS Y GASTOS
  { codigo: "60", nombre: "Compras", grupo: 6 },
  { codigo: "600", nombre: "Compras de mercaderías", grupo: 6 },
  { codigo: "601", nombre: "Compras de materias primas", grupo: 6 },
  { codigo: "602", nombre: "Compras de otros aprovisionamientos", grupo: 6 },
  { codigo: "606", nombre: "Descuentos sobre compras por pronto pago", grupo: 6 },
  { codigo: "607", nombre: "Trabajos realizados por otras empresas", grupo: 6 },
  { codigo: "608", nombre: "Devoluciones de compras y operaciones similares", grupo: 6 },
  { codigo: "609", nombre: "Rappels por compras", grupo: 6 },
  { codigo: "61", nombre: "Variación de existencias", grupo: 6 },
  { codigo: "610", nombre: "Variación de existencias de mercaderías", grupo: 6 },
  { codigo: "611", nombre: "Variación de existencias de materias primas", grupo: 6 },
  { codigo: "612", nombre: "Variación de existencias de otros aprovisionamientos", grupo: 6 },
  { codigo: "62", nombre: "Servicios exteriores", grupo: 6 },
  { codigo: "620", nombre: "Gastos en investigación y desarrollo del ejercicio", grupo: 6 },
  { codigo: "621", nombre: "Arrendamientos y cánones", grupo: 6 },
  { codigo: "622", nombre: "Reparaciones y conservación", grupo: 6 },
  { codigo: "623", nombre: "Servicios de profesionales independientes", grupo: 6 },
  { codigo: "624", nombre: "Transportes", grupo: 6 },
  { codigo: "625", nombre: "Primas de seguros", grupo: 6 },
  { codigo: "626", nombre: "Servicios bancarios y similares", grupo: 6 },
  { codigo: "627", nombre: "Publicidad, propaganda y relaciones públicas", grupo: 6 },
  { codigo: "628", nombre: "Suministros", grupo: 6 },
  { codigo: "629", nombre: "Otros servicios", grupo: 6 },
  { codigo: "63", nombre: "Tributos", grupo: 6 },
  { codigo: "630", nombre: "Impuesto sobre beneficios", grupo: 6 },
  { codigo: "631", nombre: "Otros tributos", grupo: 6 },
  { codigo: "633", nombre: "Ajustes negativos en la imposición sobre beneficios", grupo: 6 },
  { codigo: "634", nombre: "Ajustes negativos en la imposición indirecta", grupo: 6 },
  { codigo: "636", nombre: "Devolución de impuestos", grupo: 6 },
  { codigo: "638", nombre: "Ajustes positivos en la imposición sobre beneficios", grupo: 6 },
  { codigo: "639", nombre: "Ajustes positivos en la imposición indirecta", grupo: 6 },
  { codigo: "64", nombre: "Gastos de personal", grupo: 6 },
  { codigo: "640", nombre: "Sueldos y salarios", grupo: 6 },
  { codigo: "641", nombre: "Indemnizaciones", grupo: 6 },
  { codigo: "642", nombre: "Seguridad Social a cargo de la empresa", grupo: 6 },
  { codigo: "643", nombre: "Retribuciones a l/p mediante sistemas de aportación definida", grupo: 6 },
  { codigo: "644", nombre: "Retribuciones a l/p mediante sistemas de prestación definida", grupo: 6 },
  { codigo: "649", nombre: "Otros gastos sociales", grupo: 6 },
  { codigo: "65", nombre: "Otros gastos de gestión", grupo: 6 },
  { codigo: "650", nombre: "Pérdidas de créditos comerciales incobrables", grupo: 6 },
  { codigo: "651", nombre: "Resultados de operaciones en común", grupo: 6 },
  { codigo: "659", nombre: "Otras pérdidas en gestión corriente", grupo: 6 },
  { codigo: "66", nombre: "Gastos financieros", grupo: 6 },
  { codigo: "660", nombre: "Gastos financieros por actualización de provisiones", grupo: 6 },
  { codigo: "661", nombre: "Intereses de obligaciones y bonos", grupo: 6 },
  { codigo: "662", nombre: "Intereses de deudas", grupo: 6 },
  { codigo: "663", nombre: "Intereses de deudas con partes vinculadas", grupo: 6 },
  { codigo: "664", nombre: "Dividendos de acciones o participaciones como pasivos financieros", grupo: 6 },
  { codigo: "665", nombre: "Intereses por descuento de efectos y operaciones de factoring", grupo: 6 },
  { codigo: "666", nombre: "Pérdidas en participaciones y valores representativos de deuda", grupo: 6 },
  { codigo: "667", nombre: "Pérdidas de créditos no comerciales", grupo: 6 },
  { codigo: "668", nombre: "Diferencias negativas de cambio", grupo: 6 },
  { codigo: "669", nombre: "Otros gastos financieros", grupo: 6 },
  { codigo: "67", nombre: "Pérdidas procedentes de activos no corrientes y gastos excepcionales", grupo: 6 },
  { codigo: "670", nombre: "Pérdidas procedentes del inmovilizado intangible", grupo: 6 },
  { codigo: "671", nombre: "Pérdidas procedentes del inmovilizado material", grupo: 6 },
  { codigo: "672", nombre: "Pérdidas procedentes de inversiones inmobiliarias", grupo: 6 },
  { codigo: "673", nombre: "Pérdidas procedentes de participaciones a l/p en partes vinculadas", grupo: 6 },
  { codigo: "675", nombre: "Pérdidas por operaciones con obligaciones propias", grupo: 6 },
  { codigo: "678", nombre: "Gastos excepcionales", grupo: 6 },
  { codigo: "68", nombre: "Dotaciones para amortizaciones", grupo: 6 },
  { codigo: "680", nombre: "Amortización del inmovilizado intangible", grupo: 6 },
  { codigo: "681", nombre: "Amortización del inmovilizado material", grupo: 6 },
  { codigo: "682", nombre: "Amortización de las inversiones inmobiliarias", grupo: 6 },
  { codigo: "69", nombre: "Pérdidas por deterioro y otras dotaciones", grupo: 6 },
  { codigo: "690", nombre: "Pérdidas por deterioro del inmovilizado intangible", grupo: 6 },
  { codigo: "691", nombre: "Pérdidas por deterioro del inmovilizado material", grupo: 6 },
  { codigo: "692", nombre: "Pérdidas por deterioro de inversiones inmobiliarias", grupo: 6 },
  { codigo: "693", nombre: "Pérdidas por deterioro de existencias", grupo: 6 },
  { codigo: "694", nombre: "Pérdidas por deterioro de créditos por operaciones comerciales", grupo: 6 },
  { codigo: "695", nombre: "Dotación a la provisión por operaciones comerciales", grupo: 6 },
  { codigo: "696", nombre: "Pérdidas por deterioro de participaciones y valores representativos de deuda a l/p", grupo: 6 },
  { codigo: "697", nombre: "Pérdidas por deterioro de créditos a l/p", grupo: 6 },
  { codigo: "698", nombre: "Pérdidas por deterioro de participaciones y valores representativos de deuda a c/p", grupo: 6 },
  { codigo: "699", nombre: "Pérdidas por deterioro de créditos a c/p", grupo: 6 },

  // GRUPO 7 - VENTAS E INGRESOS
  { codigo: "70", nombre: "Ventas de mercaderías, de producción propia, de servicios, etc.", grupo: 7 },
  { codigo: "700", nombre: "Ventas de mercaderías", grupo: 7 },
  { codigo: "701", nombre: "Ventas de productos terminados", grupo: 7 },
  { codigo: "702", nombre: "Ventas de productos semiterminados", grupo: 7 },
  { codigo: "703", nombre: "Ventas de subproductos y residuos", grupo: 7 },
  { codigo: "704", nombre: "Ventas de envases y embalajes", grupo: 7 },
  { codigo: "705", nombre: "Prestaciones de servicios", grupo: 7 },
  { codigo: "706", nombre: "Descuentos sobre ventas por pronto pago", grupo: 7 },
  { codigo: "708", nombre: "Devoluciones de ventas y operaciones similares", grupo: 7 },
  { codigo: "709", nombre: "Rappels sobre ventas", grupo: 7 },
  { codigo: "71", nombre: "Variación de existencias", grupo: 7 },
  { codigo: "710", nombre: "Variación de existencias de productos en curso", grupo: 7 },
  { codigo: "711", nombre: "Variación de existencias de productos semiterminados", grupo: 7 },
  { codigo: "712", nombre: "Variación de existencias de productos terminados", grupo: 7 },
  { codigo: "713", nombre: "Variación de existencias de subproductos, residuos y materiales recuperados", grupo: 7 },
  { codigo: "73", nombre: "Trabajos realizados para la empresa", grupo: 7 },
  { codigo: "730", nombre: "Trabajos realizados para el inmovilizado intangible", grupo: 7 },
  { codigo: "731", nombre: "Trabajos realizados para el inmovilizado material", grupo: 7 },
  { codigo: "732", nombre: "Trabajos realizados en inversiones inmobiliarias", grupo: 7 },
  { codigo: "733", nombre: "Trabajos realizados para el inmovilizado material en curso", grupo: 7 },
  { codigo: "74", nombre: "Subvenciones, donaciones y legados", grupo: 7 },
  { codigo: "740", nombre: "Subvenciones, donaciones y legados a la explotación", grupo: 7 },
  { codigo: "746", nombre: "Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio", grupo: 7 },
  { codigo: "747", nombre: "Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio", grupo: 7 },
  { codigo: "75", nombre: "Otros ingresos de gestión", grupo: 7 },
  { codigo: "750", nombre: "Ingresos por arrendamientos", grupo: 7 },
  { codigo: "751", nombre: "Ingresos de propiedad industrial cedida en explotación", grupo: 7 },
  { codigo: "752", nombre: "Ingresos por comisiones", grupo: 7 },
  { codigo: "753", nombre: "Ingresos de propiedad inmobiliaria cedida", grupo: 7 },
  { codigo: "754", nombre: "Ingresos por servicios diversos", grupo: 7 },
  { codigo: "755", nombre: "Ingresos por servicios al personal", grupo: 7 },
  { codigo: "759", nombre: "Ingresos por servicios diversos", grupo: 7 },
  { codigo: "76", nombre: "Ingresos financieros", grupo: 7 },
  { codigo: "760", nombre: "Ingresos de participaciones en instrumentos de patrimonio", grupo: 7 },
  { codigo: "761", nombre: "Ingresos de valores representativos de deuda", grupo: 7 },
  { codigo: "762", nombre: "Ingresos de créditos", grupo: 7 },
  { codigo: "763", nombre: "Beneficios por valoración de instrumentos financieros por su valor razonable", grupo: 7 },
  { codigo: "764", nombre: "Ingresos de participaciones en partes vinculadas", grupo: 7 },
  { codigo: "765", nombre: "Ingresos de participaciones en instrumentos de patrimonio vinculadas", grupo: 7 },
  { codigo: "766", nombre: "Beneficios en participaciones y valores representativos de deuda", grupo: 7 },
  { codigo: "768", nombre: "Diferencias positivas de cambio", grupo: 7 },
  { codigo: "769", nombre: "Otros ingresos financieros", grupo: 7 },
  { codigo: "77", nombre: "Beneficios procedentes de activos no corrientes e ingresos excepcionales", grupo: 7 },
  { codigo: "770", nombre: "Beneficios procedentes del inmovilizado intangible", grupo: 7 },
  { codigo: "771", nombre: "Beneficios procedentes del inmovilizado material", grupo: 7 },
  { codigo: "772", nombre: "Beneficios procedentes de inversiones inmobiliarias", grupo: 7 },
  { codigo: "773", nombre: "Beneficios procedentes de participaciones a l/p en partes vinculadas", grupo: 7 },
  { codigo: "775", nombre: "Beneficios por operaciones con obligaciones propias", grupo: 7 },
  { codigo: "778", nombre: "Ingresos excepcionales", grupo: 7 },
  { codigo: "79", nombre: "Excesos y aplicaciones de provisiones y pérdidas por deterioro", grupo: 7 },
  { codigo: "790", nombre: "Reversión del deterioro del inmovilizado intangible", grupo: 7 },
  { codigo: "791", nombre: "Reversión del deterioro del inmovilizado material", grupo: 7 },
  { codigo: "792", nombre: "Reversión del deterioro de inversiones inmobiliarias", grupo: 7 },
  { codigo: "793", nombre: "Reversión del deterioro de existencias", grupo: 7 },
  { codigo: "794", nombre: "Reversión del deterioro de créditos por operaciones comerciales", grupo: 7 },
  { codigo: "795", nombre: "Exceso de provisiones", grupo: 7 },
  { codigo: "796", nombre: "Reversión del deterioro de participaciones y valores representativos de deuda a l/p", grupo: 7 },
  { codigo: "797", nombre: "Reversión del deterioro de créditos a l/p", grupo: 7 },
  { codigo: "798", nombre: "Reversión del deterioro de participaciones y valores representativos de deuda a c/p", grupo: 7 },
  { codigo: "799", nombre: "Reversión del deterioro de créditos a c/p", grupo: 7 },

  // GRUPO 8 - GASTOS IMPUTADOS AL PATRIMONIO NETO
  { codigo: "80", nombre: "Gastos financieros por valoración de activos y pasivos", grupo: 8 },
  { codigo: "800", nombre: "Pérdidas en activos financieros a valor razonable con cambios en el patrimonio neto", grupo: 8 },
  { codigo: "802", nombre: "Transferencia de beneficios en activos financieros a valor razonable con cambios en el patrimonio neto", grupo: 8 },
  { codigo: "81", nombre: "Gastos en operaciones de cobertura", grupo: 8 },
  { codigo: "810", nombre: "Pérdidas por coberturas de flujos de efectivo", grupo: 8 },
  { codigo: "811", nombre: "Pérdidas por coberturas de inversiones netas en negocios en el extranjero", grupo: 8 },
  { codigo: "812", nombre: "Transferencia de beneficios por coberturas de flujos de efectivo", grupo: 8 },
  { codigo: "82", nombre: "Gastos por diferencias de conversión", grupo: 8 },
  { codigo: "820", nombre: "Diferencias de conversión negativas", grupo: 8 },
  { codigo: "821", nombre: "Transferencia de diferencias de conversión positivas", grupo: 8 },
  { codigo: "83", nombre: "Impuesto sobre beneficios", grupo: 8 },
  { codigo: "830", nombre: "Impuesto sobre beneficios (si es gasto)", grupo: 8 },
  { codigo: "833", nombre: "Ajustes negativos en la imposición sobre beneficios", grupo: 8 },
  { codigo: "834", nombre: "Ingresos fiscales por diferencias permanentes", grupo: 8 },
  { codigo: "835", nombre: "Ingresos fiscales por deducciones y bonificaciones", grupo: 8 },
  { codigo: "836", nombre: "Transferencia de diferencias permanentes", grupo: 8 },
  { codigo: "837", nombre: "Transferencia de deducciones y bonificaciones", grupo: 8 },
  { codigo: "84", nombre: "Transferencias de subvenciones, donaciones y legados", grupo: 8 },
  { codigo: "840", nombre: "Transferencia de subvenciones oficiales de capital", grupo: 8 },
  { codigo: "841", nombre: "Transferencia de donaciones y legados de capital", grupo: 8 },
  { codigo: "842", nombre: "Transferencia de otras subvenciones, donaciones y legados", grupo: 8 },
  { codigo: "85", nombre: "Gastos por pérdidas actuariales y ajustes", grupo: 8 },
  { codigo: "850", nombre: "Pérdidas actuariales", grupo: 8 },
  { codigo: "851", nombre: "Ajustes negativos en activos por retribuciones a l/p de prestación definida", grupo: 8 },

  // GRUPO 9 - INGRESOS IMPUTADOS AL PATRIMONIO NETO
  { codigo: "90", nombre: "Ingresos financieros por valoración de activos y pasivos", grupo: 9 },
  { codigo: "900", nombre: "Beneficios en activos financieros a valor razonable con cambios en el patrimonio neto", grupo: 9 },
  { codigo: "902", nombre: "Transferencia de pérdidas de activos financieros a valor razonable con cambios en el patrimonio neto", grupo: 9 },
  { codigo: "91", nombre: "Ingresos en operaciones de cobertura", grupo: 9 },
  { codigo: "910", nombre: "Beneficios por coberturas de flujos de efectivo", grupo: 9 },
  { codigo: "911", nombre: "Beneficios por coberturas de inversiones netas en negocios en el extranjero", grupo: 9 },
  { codigo: "912", nombre: "Transferencia de pérdidas por coberturas de flujos de efectivo", grupo: 9 },
  { codigo: "92", nombre: "Ingresos por diferencias de conversión", grupo: 9 },
  { codigo: "920", nombre: "Diferencias de conversión positivas", grupo: 9 },
  { codigo: "921", nombre: "Transferencia de diferencias de conversión negativas", grupo: 9 },
  { codigo: "94", nombre: "Ingresos por subvenciones, donaciones y legados", grupo: 9 },
  { codigo: "940", nombre: "Ingresos de subvenciones oficiales de capital", grupo: 9 },
  { codigo: "941", nombre: "Ingresos de donaciones y legados de capital", grupo: 9 },
  { codigo: "942", nombre: "Ingresos de otras subvenciones, donaciones y legados", grupo: 9 },
  { codigo: "95", nombre: "Ingresos por ganancias actuariales y ajustes", grupo: 9 },
  { codigo: "950", nombre: "Ganancias actuariales", grupo: 9 },
  { codigo: "951", nombre: "Ajustes positivos en activos por retribuciones a l/p de prestación definida", grupo: 9 },
];

export const PGC_GRUPOS = [
  { grupo: 1, nombre: "Financiación básica" },
  { grupo: 2, nombre: "Activo no corriente" },
  { grupo: 3, nombre: "Existencias" },
  { grupo: 4, nombre: "Acreedores y deudores por operaciones comerciales" },
  { grupo: 5, nombre: "Cuentas financieras" },
  { grupo: 6, nombre: "Compras y gastos" },
  { grupo: 7, nombre: "Ventas e ingresos" },
  { grupo: 8, nombre: "Gastos imputados al patrimonio neto" },
  { grupo: 9, nombre: "Ingresos imputados al patrimonio neto" },
];

export default PGC;
